### PR TITLE
Add rn-test module for testing

### PR DESCRIPTION
**Pull request by RangerMauve**
Changes proposed in this pull request:
- Added rn-tape CLI for testing react-native
- Removed react-native related code in `./e2e/`
- Added `react-native` file to test folder for react-native specific tests

@consento-org/maintainer

### CODE REVIEW

**Comment by RangerMauve** [comment]
@martinheidegger Is this good to merge?

**Comment by martinheidegger** [comment]
Lets go for it! This is awesome `-3871 loc`

**Comment by RangerMauve** [comment]
Did this get published on NPM by any chance?

**Comment by martinheidegger** [comment]
As this PR doesn't have any impact on the packaged code, I didn't publish it, did I mistake something?

**Pull request merged**
